add replace

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -34,6 +34,20 @@ function source_path() {
   done
 }
 
+## replace vi nvim vim
+function replace() {
+  if [[ $# -lt 2 ]]; then
+    echo "arguments error" >&2
+    return 1
+  fi
+  which $2>/dev/null
+  if [[ $? -eq 0 ]]; then
+    alias $1=$2
+  elif [[ $# -eq 3 ]]; then
+    alias $1=$3
+  fi
+}
+
 append_path /sbin /usr/sbin /usr/local/sbin
 append_path $HOME/bin $HOME/git/note/bin
 
@@ -53,24 +67,9 @@ alias watch='watch -d -n 1'
 alias tuer="ps x | fzf | awk '{print \$1}' | xargs kill -9"
 alias tmux="TERM=screen-256color-bce tmux"
 
-which nvim >/dev/null
-if [[ $? -eq 0 ]]; then
-  alias vi="nvim"
-else
-  alias vi="vim"
-fi
-
-which fd >/dev/null
-if [ $? -ne 0 ]; then
-  alias fd="fdfind"
-fi
-
-alias ll="ls -l"
-if [[ "x$os" == "xmac" ]]; then
-  alias ls="ls -G"
-else
-  alias ls="ls --color=auto"
-fi
+replace vi nvim vim
+replace fd fdfind
+replace ls exa
 
 export no_proxy="localhost,127.0.0.1,$ip"
 
@@ -230,7 +229,11 @@ function pdf() {
   tex=`echo $1 | awk -F. '{print $1}'`
 
   xelatex $tex
-  asy $tex*.asy
+  if [[ -d asytmp ]]; then
+    cd asytmp
+    asy $tex*.asy
+    cd -
+  fi
   bibtex $tex
   xelatex $tex
   xelatex $tex  ## update cref
